### ISSUE TITLE
Not Working Example

### ISSUE THREAD

**Issue by mbta009** [ffosilva/AES32#3]
Hello Dear @ffosilva 
Thanks for building this Lib which enables the use of ESP32 internal encryption capability. The output of the example code test result is as follows. The text is not decrypted.

`Encrypted message: 0100000000000000000000000000000000000000000000007856ADBA39D1FD3F
Encrypted length (iv + message + padding): 32
Decrypted message: 
Decrypted length (message + padding): 16

`

**Comment by mbta009** [comment]
I found the problem to set the key is not written.

aes32.setKey (aes_key, 128);

**Comment by ffosilva** [comment]
Hi @mbta009! Thank you for your issue report. Could you please create a pull request to fix this issue? Thank you.
